### ISSUE TITLE
Question - Building image with plugins

### ISSUE THREAD

**Issue by franrebo84** [bitnami/bitnami-docker-redmine#102]
**Description**
Im trying to build my own enviroment with customs plugins, but I got this error with docker build after the rake command in my dockefile: 

**Steps to reproduce the issue:**

1. docker build -t redmine:test3 .

This is my (poor) docker file:
```
FROM bitnami/redmine
COPY application.css /opt/bitnami/redmine/public/themes/classic/stylesheets/application.css
# Instalacion de Plugins
RUN /usr/sbin/install_packages make ruby-dev gcc libmysqlclient-dev libmagickwand-dev imagemagick libpq-dev && \
    cd /opt/bitnami/redmine && \
    /app-entrypoint.sh /opt/bitnami/git/bin/git clone http://github.com:/jperelli/Redmine-Periodic-Task.git plugins/periodictask && \
    /app-entrypoint.sh /opt/bitnami/ruby/bin/bundle install --no-deployment && \
    /app-entrypoint.sh /opt/bitnami/ruby/bin/bundle exec rake redmine:plugins:migrate NAME=periodictask RAILS_ENV=production
```

**Describe the results you received:**

```
rake aborted!
Mysql2::Error: Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' (2)
/opt/bitnami/redmine/app/models/custom_field.rb:38:in `<class:CustomField>'
/opt/bitnami/redmine/app/models/custom_field.rb:18:in `<top (required)>'
/opt/bitnami/redmine/lib/redmine/field_format.rb:108:in `field_attributes'
/opt/bitnami/redmine/lib/redmine/field_format.rb:111:in `<class:Base>'
/opt/bitnami/redmine/lib/redmine/field_format.rb:57:in `<module:FieldFormat>'
/opt/bitnami/redmine/lib/redmine/field_format.rb:21:in `<module:Redmine>'
/opt/bitnami/redmine/lib/redmine/field_format.rb:20:in `<top (required)>'
/opt/bitnami/redmine/lib/redmine.rb:40:in `<top (required)>'
/opt/bitnami/redmine/config/initializers/30-redmine.rb:6:in `<top (required)>'
/opt/bitnami/redmine/config/environment.rb:14:in `<top (required)>'
/opt/bitnami/redmine/plugins/periodictask/lib/tasks/periodictask.rake:7:in `require'
/opt/bitnami/redmine/plugins/periodictask/lib/tasks/periodictask.rake:7:in `<top (required)>'
/opt/bitnami/redmine/lib/tasks/redmine.rake:194:in `load'
/opt/bitnami/redmine/lib/tasks/redmine.rake:194:in `block in <top (required)>'
/opt/bitnami/redmine/lib/tasks/redmine.rake:194:in `each'
/opt/bitnami/redmine/lib/tasks/redmine.rake:194:in `<top (required)>'
/opt/bitnami/redmine/Rakefile:7:in `<top (required)>'
/opt/bitnami/ruby/bin/bundle:23:in `load'
/opt/bitnami/ruby/bin/bundle:23:in `<main>'
(See full trace by running task with --trace)
```

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

**Version**

- Output of `docker version`:

```
Client:
 Version:      18.05.0-ce
 API version:  1.37
 Go version:   go1.9.5
 Git commit:   f150324
 Built:        Wed May  9 22:14:54 2018
 OS/Arch:      linux/amd64
 Experimental: false
 Orchestrator: swarm

Server:
 Engine:
  Version:      18.05.0-ce
  API version:  1.37 (minimum version 1.12)
  Go version:   go1.9.5
  Git commit:   f150324
  Built:        Wed May  9 22:18:36 2018
  OS/Arch:      linux/amd64
  Experimental: false
```

- Output of `docker info`:

```
Client:
 Version:      18.05.0-ce
 API version:  1.37
 Go version:   go1.9.5
 Git commit:   f150324
 Built:        Wed May  9 22:14:54 2018
 OS/Arch:      linux/amd64
 Experimental: false
 Orchestrator: swarm

Server:
 Engine:
  Version:      18.05.0-ce
  API version:  1.37 (minimum version 1.12)
  Go version:   go1.9.5
  Git commit:   f150324
  Built:        Wed May  9 22:18:36 2018
  OS/Arch:      linux/amd64
  Experimental: false
[root@franux redmine_in_house]# docker info
Containers: 7
 Running: 1
 Paused: 0
 Stopped: 6
Images: 14
Server Version: 18.05.0-ce
Storage Driver: overlay2
 Backing Filesystem: xfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 773c489c9c1b21a6d78b5c538cd395416ec50f88
runc version: 4fc53a81fb7c994640722ac585fa9ca548971871
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 3.10.0-862.3.2.el7.x86_64
Operating System: CentOS Linux 7 (Core)
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 1.796GiB
Name: franux
ID: SAW4:F5SR:SL6H:AWH6:N5GI:BBLI:FJHE:2N5O:NQ4L:EB3A:CNLK:HSZT
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

WARNING: bridge-nf-call-iptables is disabled
WARNING: bridge-nf-call-ip6tables is disabled
```

**Comment by tompizmor** [comment]
Hello @franrebo84,

The issue is that any database is running at that point so the `db:migrate` command fails.

However, you don't need to execute that command as it will be executed  in the first run of Redmine (you can search `Migrating database...` in the logs)

So I have tried with this Dockerfile and docker-compose.yml and it seems to work fine:

```
FROM bitnami/redmine
COPY application.css /opt/bitnami/redmine/public/themes/classic/stylesheets/application.css
# Instalacion de Plugins
RUN /usr/sbin/install_packages make ruby-dev gcc libmysqlclient-dev libmagickwand-dev imagemagick libpq-dev

WORKDIR /opt/bitnami/redmine

RUN /opt/bitnami/git/bin/git clone http://github.com:/jperelli/Redmine-Periodic-Task.git plugins/periodictask && \
    /opt/bitnami/ruby/bin/bundle install --no-deployment --without test --without development RAILS_ENV=production

ENV RAILS_ENV="production"
```

and

```
version: '2'
services:
  mariadb:
    image: 'bitnami/mariadb:latest'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
  redmine:
    image: YOUR_IMAGE
    ports:
      - '80:3000'
    depends_on:
      - mariadb
```

**Comment by franrebo84** [comment]
Thanks @tompizmor !! I'll try that!

**Comment by tompizmor** [comment]
ok, let me know if you have any issue!

**Comment by franrebo84** [comment]
It worked!!
Thanks so much @tompizmor!
