### ISSUE TITLE
latest redmine-images break my setup behind apache proxy

### ISSUE THREAD

**Issue by stefangweichinger** [bitnami/bitnami-docker-redmine#119]
```
$ cat docker-compose.yml 
version: '2'

services:

  mariadb:
    image: 'bitnami/mariadb:latest'
    environment:
      - MARIADB_ROOT_PASSWORD=OClskdE
    volumes:
      - 'redmine-bitnami-db:/bitnami'
  redmine:
    image: bitnami/redmine:latest
    #image: bitnami/redmine:4.0.2-debian-9-r23
    environment:
      - REDMINE_USERNAME=sgw
      - REDMINE_PASSWORD=hidden
      - REDMINE_DB_PASSWORD=Hidden
      - SMTP_HOST=oc.some.at
      - SMTP_PORT=587
      - SMTP_USER=oc@oc.some.at
      - SMTP_PASSWORD=2shshshsjhsh
      - SMTP_TLS=true
    ports:
      - '3001:3000'
    volumes:
      - 'redmine-bitnami-app:/bitnami'
      - './config.ru:/opt/bitnami/redmine/config.ru'
      - './public/themes:/opt/bitnami/redmine/public/themes'

volumes:
 redmine-bitnami-db:
 redmine-bitnami-app:
```

latest redmine-images fail for me, I get no working app and the error is:

```
redmine_1  | Started GET "/redmine" for 2001:470:6f:333:5e17:f456:d0db:d228 at 2019-03-22 15:25:06 +0000
redmine_1  |   
redmine_1  | ActionController::RoutingError (No route matches [GET] "/redmine"):
redmine_1  |   
redmine_1  | vendor/bundle/ruby/2.4.0/gems/actionpack-5.2.2/lib/action_dispatch/middleware/debug_exceptions.rb:65:in `call'
redmine_1  | vendor/bundle/ruby/2.4.0/gems/actionpack-5.2.2/lib/action_dispatch/middleware/show_exceptions.rb:33:in `call'
redmine_1  | vendor/bundle/ruby/2.4.0/gems/railties-5.2.2/lib/rails/rack/logger.rb:38:in `call_app'
redmine_1  | vendor/bundle/ruby/2.4.0/gems/railties-5.2.2/lib/rails/rack/logger.rb:26:in `block in call'
redmine_1  | vendor/bundle/ruby/2.4.0/gems/activesupport-5.2.2/lib/active_support/tagged_logging.rb:71:in `block in tagged'
redmine_1  | vendor/bundle/ruby/2.4.0/gems/activesupport-5.2.2/lib/active_support/tagged_logging.rb:28:in `tagged'
redmine_1  | vendor/bundle/ruby/2.4.0/gems/activesupport-5.2.2/lib/active_support/tagged_logging.rb:71:in `tagged'
redmine_1  | vendor/bundle/ruby/2.4.0/gems/railties-5.2.2/lib/rails/rack/logger.rb:26:in `call'
redmine_1  | vendor/bundle/ruby/2.4.0/gems/actionpack-5.2.2/lib/action_dispatch/middleware/remote_ip.rb:81:in `call'
redmine_1  | vendor/bundle/ruby/2.4.0/gems/actionpack-5.2.2/lib/action_dispatch/middleware/request_id.rb:27:in `call'
redmine_1  | vendor/bundle/ruby/2.4.0/gems/rack-2.0.6/lib/rack/method_override.rb:22:in `call'
redmine_1  | vendor/bundle/ruby/2.4.0/gems/rack-2.0.6/lib/rack/runtime.rb:22:in `call'
redmine_1  | vendor/bundle/ruby/2.4.0/gems/activesupport-5.2.2/lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'
redmine_1  | vendor/bundle/ruby/2.4.0/gems/actionpack-5.2.2/lib/action_dispatch/middleware/executor.rb:14:in `call'
redmine_1  | vendor/bundle/ruby/2.4.0/gems/actionpack-5.2.2/lib/action_dispatch/middleware/static.rb:127:in `call'
[..]
```

my setup is also described in #107 ... I run it proxied behind apache.
So to me it seems that the behavior has been changed upstream.

In the above yml you see a line pointing to a image that works for me.
":latest" does not.

https://oc.oops.co.at/redmine/   ... is the URL used

and forwarded in the vhost:

```
<Location /redmine>
    ProxyPass http://127.0.0.1:3001/redmine
    ProxyPassReverse http://127.0.0.1:3001/redmine
    Require all granted
    </Location>
```

The mapped config.ru:

```
$ cat config.ru 
# This file is used by Rack-based servers to start the application.

require ::File.expand_path('../config/environment',  __FILE__)
map ActionController::Base.config.try(:relative_url_root) || "/" do
run Rails.application
end
```

I'll be happy to provide more infos if needed. Thanks!

**Comment by andresbono** [comment]
Hi @stefangweichinger, we stopped persisting most of the Redmine configuration files to avoid issues when performing upgrades between Redmine versions (see #109).

If you remember from #107, you added a line at the bottom of the `/bitnami/redmine/conf/environment.rb` file:

```ruby
Redmine::Utils::relative_url_root = "/redmine"
```

However, the `/bitnami/redmine/conf/environment.rb` file is not read anymore since you upgraded the container.

---

To solve it, you can try the following?

- Modify the `config.ru` file to include the prefix. It will look like the following snippet:

```ruby
# This file is used by Rack-based servers to start the application.

require ::File.expand_path('../config/environment',  __FILE__)
map "/redmine" do
run Rails.application
end
```

- Restart Redmine:

```
docker-compose restart redmine
```

Let us know if it solves the issue.

**Comment by stefangweichinger** [comment]
I substituted the old block as seen here:

```
# require ::File.expand_path('../config/environment',  __FILE__)
# map ActionController::Base.config.try(:relative_url_root) || "/" do
# run Rails.application
# end

require ::File.expand_path('../config/environment',  __FILE__)
map "/redmine" do
run Rails.application
end
```

Re-pulled the images, started the "stack". I get the login but the path to the css or so seems still wrong, so the GUI is missing correct format etc

```
  redmine:
    image: bitnami/redmine:latest
    #image: bitnami/redmine:4.0.2-debian-9-r23
    environment:
      - REDMINE_USERNAME=sgw
      - REDMINE_PASSWORD=admin
      - REDMINE_DB_PASSWORD=xxx
      - SMTP_HOST=oc.xxx
      - SMTP_PORT=587
      - SMTP_USER=oc@oc.xxx
      - SMTP_PASSWORD=xxx
      - SMTP_TLS=true
    ports:
      - '3001:3000'
    volumes:
      - 'redmine-bitnami-app:/bitnami'
      - './config.ru:/opt/bitnami/redmine/config.ru'
      - './public/themes:/opt/bitnami/redmine/public/themes'
```

maybe it is related to my usage of additional themes, see volume-definition above.

**Comment by andresbono** [comment]
Does your theme load all the css and additional resources if you do the following?

- Restore the contents of `config.ru` to the original version:

```ruby
# This file is used by Rack-based servers to start the application.

require ::File.expand_path('../config/environment',  __FILE__)
map ActionController::Base.config.try(:relative_url_root) || "/" do
  run Rails.application
end
```
- In the container, modify the `/opt/bitnami/redmine/config/environment.rb` to add the following line at the bottom:

```
Redmine::Utils::relative_url_root = "/redmine"
```

- Restart the Redmine container:

```
docker-compose restart redmine
```

Once you confirm this works for you, we can check what we can do to persist/apply your changes in the `environment.rb` file.

**Comment by stefangweichinger** [comment]
Sidenote: I wasn't using any non-default theme anyway. It was just prepared for that.
Yes: your suggested changes make things work again with bitnami/redmine:latest
Nice. Now for the persistence. I assume I will have to "mount" that environment.rb from the host as I do for config.ru ?

**Comment by stefangweichinger** [comment]
today's new image broke it again. reusing older working image for now.

**Comment by andresbono** [comment]
Hi @stefangweichinger,

I think you mounted the `environment.rb` file in the wrong path. It should be in the `/opt/bitnami/redmine/config/`. However, that would not work either if the container needs to be initialized from the beginning.

You can try the following:

- Modify the `rootfs/run.sh` file to add an `echo` that will write at the bottom of the `environment.rb` file. The line should be added right before the Redmine start:

```shell
...
chmod -R 1777 /opt/bitnami/redmine/tmp

echo 'Redmine::Utils::relative_url_root = "/redmine"' >> /opt/bitnami/redmine/config/environment.rb

info "Starting redmine..."
...
```

- Mount the `rootfs/run.sh` file in your docker-compose:

```
    volumes:
      - 'redmine-bitnami-app:/bitnami'
      - './config.ru:/opt/bitnami/redmine/config.ru'
      - './rootfs.run.sh:/run.sh'
      - './public/themes:/opt/bitnami/redmine/public/themes'
```

- Restart Redmine

```
docker-compose restart redmine
```

Hope you find this useful.

**Comment by stefangweichinger** [comment]
That fails with a permission denied for run.sh first, for sure I had to "chmod +x", now it works again, thanks.
Let's wait for tomorrow ,-)

**Comment by andresbono** [comment]
Did it work for you, @stefangweichinger?

**Comment by stefangweichinger** [comment]
Yes, tonight's re-pulled latest image still works. looks good, thanks

**Comment by andresbono** [comment]
Great!

Closing the issue.

**Comment by stefangweichinger** [comment]
I hit issues around this setup again now that I try to upgrade to 4.2.3. I think it would make sense to continue here?
Currently 4.2.3 runs (after editing database.yml), but css is broken. I assume config.ru is wrong.

Current try:

```
# config.ru 
# This file is used by Rack-based servers to start the application.

require ::File.expand_path('../config/environment',  __FILE__)
map ActionController::Base.config.try(:relative_url_root) || "/" do
run Rails.application
end

require ::File.expand_path('../config/environment',  __FILE__)
map "/redmine" do
run Rails.application
end
```

**Comment by stefangweichinger** [comment]
To me it seems that that "echo" command does not work correctly anymore, so `environment.rb` does not contain 'Redmine::Utils::relative_url_root = "/redmine"' right now. Trying to fix that.

**Comment by stefangweichinger** [comment]
current fix:

commented the lines 2 and 3 here (these scripts don't exist anymore in the current image `bitnami/redmine:4.2.3-debian-10-r42`

```

 cat rootfs.run.sh 
#!/bin/bash -e
#. /opt/bitnami/base/functions
#. /opt/bitnami/base/helpers

USER=redmine
RAILS_ENV=production
PID_FILE=/opt/bitnami/redmine/tmp/pids/redmine.pid
LOG_FILE=/opt/bitnami/redmine/logs/production.log

mkdir -p /opt/bitnami/redmine/tmp/pids
chown ${USER}: -R /opt/bitnami/redmine/tmp
chmod -R 1777 /opt/bitnami/redmine/tmp

echo 'Redmine::Utils::relative_url_root = "/redmine"' >> /opt/bitnami/redmine/config/environment.rb

info "Starting redmine..."
cd /opt/bitnami/redmine || exit 1
exec gosu ${USER} bundle exec passenger start -e ${RAILS_ENV} --pid-file ${PID_FILE} --log-file ${LOG_FILE} -p 3000
```

suggestions welcome, I think my setup is a bit redundant maybe (defining that URL in multiple places).

**Comment by stefangweichinger** [comment]
@miguelaeh sure, sorry. So far I used `bitnami/redmine:4.2.1-debian-10-r21`.

What I found out in the meantime is that `run.sh` has a different location now.

```
# old
- './rootfs.run.sh:/run.sh'

# now I try

- './rootfs.run-4.2.3.sh:/opt/bitnami/scripts/redmine/run.sh'
```

And I took the `run.sh` from this repo, and modified it like:

```
## rootfs.run-4.2.3.sh 
#!/bin/bash

# shellcheck disable=SC1090,SC1091

set -o errexit
set -o nounset
set -o pipefail
# set -o xtrace # Uncomment this line for debugging purpose

# Load Redmine environment
. /opt/bitnami/scripts/redmine-env.sh

# Load libraries
. /opt/bitnami/scripts/libos.sh
. /opt/bitnami/scripts/liblog.sh
. /opt/bitnami/scripts/libredmine.sh

USER=redmine
RAILS_ENV=production
PID_FILE=/opt/bitnami/redmine/tmp/pids/redmine.pid
LOG_FILE=/opt/bitnami/redmine/logs/production.log

mkdir -p /opt/bitnami/redmine/tmp/pids
chown ${USER}: -R /opt/bitnami/redmine/tmp
chmod -R 1777 /opt/bitnami/redmine/tmp

echo 'Redmine::Utils::relative_url_root = "/redmine"' >> /opt/bitnami/redmine/config/environment.rb

cd "$REDMINE_BASE_DIR"

declare -a cmd=(
        "bundle" "exec" "passenger" "start"
        "--user" "$REDMINE_DAEMON_USER"
        "-e" "$REDMINE_ENV"
        "-p" "$REDMINE_PORT_NUMBER"
        )

info "** Starting Redmine **"
exec "${cmd[@]}" "$@"
```

This seems to work in my first tests. Any thoughts?

**Comment by miguelaeh** [comment]
Hi @stefangweichinger ,
I think you were using a really old image, probably your issues comes from the image refactorization explained here: https://github.com/bitnami/bitnami-docker-redmine#421-debian-10-r70

**Comment by stefangweichinger** [comment]
@miguelaeh thanks for the pointer. Yes, it was a rather big upgrade step ;-) So far it works, great.
