### ISSUE TITLE
New Installation - Complete Failure To Initialize

### ISSUE THREAD

**Issue by LeeThompson** [bitnami/bitnami-docker-redmine#154]
**Description**

Starting bitnami-redmine container for the first time.

**Describe the results you received:**

Lots of errors and container halted.
All referenced additional logs are attached.

```
undefined:1
SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at Registry.load (/opt/bitnami/nami/node_modules/nami-core/lib/registry.js:251:25)
    at new Registry (/opt/bitnami/nami/node_modules/nami-core/lib/registry.js:58:10)
    at new Manager (/opt/bitnami/nami/node_modules/nami-core/lib/manager.js:109:22)
    at new NamiCliApp (/opt/bitnami/nami/cli/nami-app.js:61:20)
    at Object.<anonymous> (/opt/bitnami/nami/index.js:7:14)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
[0m[38;5;2mINFO [0m ==> Starting gosu... 
[0m[38;5;2mINFO [0m ==> Starting redmine...
 [passenger_native_support.so] trying to compile for the current user (redmine) and Ruby interpreter...
     (set PASSENGER_COMPILE_NATIVE_SUPPORT_BINARY=0 to disable)
     Warning: compilation didn't succeed. To learn why, read this file:
     /tmp/passenger_native_support-a89ms8.log
 [passenger_native_support.so] finding downloads for the current Ruby interpreter...
     (set PASSENGER_DOWNLOAD_NATIVE_SUPPORT_BINARY=0 to disable)
     Could not download https://github.com/phusion/passenger/releases/download/release-6.0.4/rubyext-ruby-2.6.6-x86_64-linux.tar.gz: The requested URL returned error: 404 Not Found
     Trying next mirror...
     Could not download https://oss-binaries.phusionpassenger.com/binaries/passenger/by_release/6.0.4/rubyext-ruby-2.6.6-x86_64-linux.tar.gz: The requested URL returned error: 404 
     Trying next mirror...
     Could not download https://s3.amazonaws.com/phusion-passenger/binaries/passenger/by_release/6.0.4/rubyext-ruby-2.6.6-x86_64-linux.tar.gz: The requested URL returned error: 403 Forbidden
 [passenger_native_support.so] will not be used (can't compile or download) 
  --> Passenger will still operate normally.
*** ERROR: the Nginx configuration that Phusion Passenger Standalone generated internally contains problems. The error message returned by the Nginx engine is:

    nginx: the configuration file nginx.conf syntax is ok
    nginx: [emerg] open() "/opt/bitnami/redmine/logs/production.log" failed (13: Permission denied)
    nginx: configuration file nginx.conf test failed

This probably means that you have found a bug in Phusion Passenger Standalone. Please report this bug to our Github issue tracker: https://github.com/phusion/passenger/issues

In the bug report, please include this error message, as well as the contents of the file /tmp/passenger-standalone-8imt7k.log
```

**Describe the results you expected:**

Redmine to start.

**Version**

Docker v18.09.8, build bfed4f5 (Synology)
Bitnami Image Version: 4.1.1-debian-10-r104

[redmine.log](https://github.com/bitnami/bitnami-docker-redmine/files/5014458/redmine.log)
[passenger_native_support-a89ms8.log](https://github.com/bitnami/bitnami-docker-redmine/files/5014481/passenger_native_support-a89ms8.log)
[passenger-standalone-8imt7k.log](https://github.com/bitnami/bitnami-docker-redmine/files/5014473/passenger-standalone-8imt7k.log)

**Comment by LeeThompson** [comment]
I'm going to nuke this container and start again.

**Comment by joancafom** [comment]
Hi @LeeThompson 

Could you provide with some more details on how are you starting this so as to be able to reproduce the issue locally? What are the steps you are following? Are you using docker or docker-compose? In this last case, are you using a custom `docker-compose.yml` file or the standard one?

Thanks!

**Comment by LeeThompson** [comment]
@joancafom I'm sorry I deleted the container and I'm using the official one.   But for the install experience:

Running Docker on a Synology DS1817+.  (It runs a somewhat customized version of Debian)
There is (via the web admin) a GUI for Docker (https://www.synology.com/en-us/dsm/feature/docker).  I do not know if it uses docker-compose behind the scenes or not.

My configuration was very standard:
1. Had it pull the image bitnami/redmine (tag: latest) from Docker hub.
2. Created the container as recommended in the documentation on Docker hub.
3. Mapped a local folder on the Synology to `/bitnami` path for the container to have persistent data ( no files ever appeared in that path).
4. I had already setup a MariaDB container for Redmine and linked the Bitnami Redmine container to it.
5. Filled in the environment variables (using the Synology Docker GUI) for the Redmine container.
6. It connected to mariadb fine but then went into the logs you see attached to the issue.

I later deleted the container and redid the above steps from Step 2 and got a different error, that time I got https://github.com/bitnami/bitnami-docker-redmine/issues/113.

After that I gave up and now I'm running it using redmine:latest (official).   (I had wanted to use this one because the official crazily doesn't let configuration.yml exist in a persistent location, and you guys had all the SMTP stuff in env variables which was handy).

**Comment by joancafom** [comment]
Hi @LeeThompson 

No problem! I have tried to replicate your issue but unfortunately I was unable to. It is true indeed that I was able to see some of the logs you mentioned (the ones related with the downloads) but eventually the container was able to start up with no issues. I have also tried to map a local folder as stated, and even restarted the container and still nothing. I don't really know much about Synology's solution, but could it be the case that this is due the solution they are using?

**Comment by huytn** [comment]
same issue, here is logs:

```
Welcome to the Bitnami redmine container
Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-redmine
Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-redmine/issues

nami    INFO  Initializing redmine
redmine INFO  Configuring Redmine database...
mysql-c INFO  Trying to connect to MySQL server
mysql-c INFO  Found MySQL server listening at mariadb:3306
mysql-c INFO  MySQL server listening and working at mariadb:3306
redmine INFO  Preparing Redmine environment...
redmine INFO  Generating new secret...
redmine INFO  Migrating database...
redmine INFO
redmine INFO  ########################################################################
redmine INFO   Installation parameters for redmine:
redmine INFO     Username: user
redmine INFO     Password: **********
redmine INFO   (Passwords are not shown for security reasons)
redmine INFO  ########################################################################
redmine INFO
nami    INFO  redmine successfully initialized
INFO  ==> Starting gosu...
INFO  ==> Starting redmine...
 [passenger_native_support.so] trying to compile for the current user (redmine) and Ruby interpreter...
     (set PASSENGER_COMPILE_NATIVE_SUPPORT_BINARY=0 to disable)
     Warning: compilation didn't succeed. To learn why, read this file:
     /tmp/passenger_native_support-1u889mr.log
 [passenger_native_support.so] finding downloads for the current Ruby interpreter...
     (set PASSENGER_DOWNLOAD_NATIVE_SUPPORT_BINARY=0 to disable)
     Could not download https://github.com/phusion/passenger/releases/download/release-6.0.4/rubyext-ruby-2.6.6-x86_64-linux.tar.gz: The requested URL returned error: 404 Not Found
     Trying next mirror...
     Could not download https://oss-binaries.phusionpassenger.com/binaries/passenger/by_release/6.0.4/rubyext-ruby-2.6.6-x86_64-linux.tar.gz: The requested URL returned error: 404
     Trying next mirror...
     Could not download https://s3.amazonaws.com/phusion-passenger/binaries/passenger/by_release/6.0.4/rubyext-ruby-2.6.6-x86_64-linux.tar.gz: The requested URL returned error: 403 Forbidden
 [passenger_native_support.so] will not be used (can't compile or download)
  --> Passenger will still operate normally.
=============== Phusion Passenger Standalone web server started ===============
PID file: /opt/bitnami/redmine/tmp/pids/redmine.pid
Log file: /opt/bitnami/redmine/logs/production.log
Environment: production
Accessible via: http://0.0.0.0:3000/

You can stop Phusion Passenger Standalone by pressing Ctrl-C.
Problems? Check https://www.phusionpassenger.com/library/admin/standalone/troubleshooting/
===============================================================================
[ N 2020-11-04 11:16:59.1931 88/T5 age/Cor/SecurityUpdateChecker.h:519 ]: Security update check: no update found (next check in 24 hours)
[ N 2020-11-04 11:16:59.1931 88/T5 age/Cor/SecurityUpdateChecker.h:519 ]: Security update check: no update found (next check in 24 hours)
App 123 output:  [passenger_native_support.so] trying to compile for the current user (redmine) and Ruby interpreter...
App 123 output:      (set PASSENGER_COMPILE_NATIVE_SUPPORT_BINARY=0 to disable)
App 123 output:  [passenger_native_support.so] trying to compile for the current user (redmine) and Ruby interpreter...
App 123 output:      (set PASSENGER_COMPILE_NATIVE_SUPPORT_BINARY=0 to disable)
App 123 output:      Warning: compilation didn't succeed. To learn why, read this file:
App 123 output:      /tmp/passenger_native_support-1etnrab.log
App 123 output:  [passenger_native_support.so] finding downloads for the current Ruby interpreter...
App 123 output:      (set PASSENGER_DOWNLOAD_NATIVE_SUPPORT_BINARY=0 to disable)
App 123 output:      Warning: compilation didn't succeed. To learn why, read this file:
App 123 output:      /tmp/passenger_native_support-1etnrab.log
App 123 output:  [passenger_native_support.so] finding downloads for the current Ruby interpreter...
App 123 output:      (set PASSENGER_DOWNLOAD_NATIVE_SUPPORT_BINARY=0 to disable)
App 123 output:      Could not download https://github.com/phusion/passenger/releases/download/release-6.0.4/rubyext-ruby-2.6.6-x86_64-linux.tar.gz: The requested URL returned error: 404 Not Found
App 123 output:      Trying next mirror...
App 123 output:      Could not download https://github.com/phusion/passenger/releases/download/release-6.0.4/rubyext-ruby-2.6.6-x86_64-linux.tar.gz: The requested URL returned error: 404 Not Found
App 123 output:      Trying next mirror...
App 123 output:      Could not download https://oss-binaries.phusionpassenger.com/binaries/passenger/by_release/6.0.4/rubyext-ruby-2.6.6-x86_64-linux.tar.gz: The requested URL returned error: 404
App 123 output:      Trying next mirror...
App 123 output:      Could not download https://oss-binaries.phusionpassenger.com/binaries/passenger/by_release/6.0.4/rubyext-ruby-2.6.6-x86_64-linux.tar.gz: The requested URL returned error: 404
App 123 output:      Trying next mirror...
App 123 output:      Could not download https://s3.amazonaws.com/phusion-passenger/binaries/passenger/by_release/6.0.4/rubyext-ruby-2.6.6-x86_64-linux.tar.gz: The requested URL returned error: 403 Forbidden
App 123 output:  [passenger_native_support.so] will not be used (can't compile or download)
App 123 output:   --> Passenger will still operate normally.
App 123 output:      Could not download https://s3.amazonaws.com/phusion-passenger/binaries/passenger/by_release/6.0.4/rubyext-ruby-2.6.6-x86_64-linux.tar.gz: The requested URL returned error: 403 Forbidden
App 123 output:  [passenger_native_support.so] will not be used (can't compile or download)
App 123 output:   --> Passenger will still operate normally.
Creating scope :system. Overwriting existing method Enumeration.system.
Creating scope :system. Overwriting existing method Enumeration.system.
Creating scope :sorted. Overwriting existing method Group.sorted.
Creating scope :sorted. Overwriting existing method User.sorted.
Creating scope :sorted. Overwriting existing method Group.sorted.
Creating scope :sorted. Overwriting existing method User.sorted.
Started HEAD "/" for 127.0.0.1 at 2020-11-04 11:18:07 +0000
Processing by WelcomeController#index as HTML
Started HEAD "/" for 127.0.0.1 at 2020-11-04 11:18:07 +0000
Processing by WelcomeController#index as HTML
  Current user: anonymous
Redirected to http://0.0.0.0/login?back_url=http%3A%2F%2F0.0.0.0%2F
Filter chain halted as :check_if_login_required rendered or redirected
Completed 302 Found in 303ms (ActiveRecord: 24.5ms)
  Current user: anonymous
Redirected to http://0.0.0.0/login?back_url=http%3A%2F%2F0.0.0.0%2F
Filter chain halted as :check_if_login_required rendered or redirected
Completed 302 Found in 303ms (ActiveRecord: 24.5ms)
```

and here is docker-compose.yaml

```
version: '2'
services:
  redmine:
    image: 'docker.io/bitnami/redmine:4-debian-10'
    ports:
      - '80:3000'
    environment:
      - REDMINE_DB_MYSQL=mariadb
      - REDMINE_DB_NAME=redmine
      - REDMINE_DB_USERNAME=redmine
      - REDMINE_DB_PASSWORD=redmine
      - REDMINE_NO_DB_MIGRATE=false
      - SMTP_HOST=mailserver.com
      - SMTP_PORT=25
      - SMTP_DOMAIN=mailserver.com
      - SMTP_TLS=false
    volumes:
      - 'redmine_data:/bitnami/redmine'
    depends_on:
      - mariadb
    links:
      - mariadb
    networks:
      - redmine_network

  mariadb:
    image: 'docker.io/bitnami/mariadb:10.3-debian-10'
    environment:
      - MARIADB_ROOT_USER=redmine
      - MARIADB_ROOT_PASSWORD=redmine
    volumes:
      - 'mariadb-data:/bitnami/mariadb'
      - ./redmine_2.5.2.sql:/docker-entrypoint-initdb.d/0_init.sql
    networks:
      - redmine_network

volumes:
  mariadb-data:
    driver: local
  redmine_data:
    driver: local

networks:
  redmine_network:
    driver: "bridge"
    attachable: true
```

**Comment by marcosbc** [comment]
Hi @huytn, in your case it seems it is only showing a warning, as the Redmine container seems to run successfully. Could you confirm that it works and does not exit?

This is something we can fix on our side by compiling Redmine / Passenger native library with the same Ruby version than the one being currently used in the image. I've just re-launched the compilation process with the hopes of this being fixed during this weekend.
