### ISSUE TITLE
[Redmine] Pod crash after restart

### ISSUE THREAD

**Issue by nomopo45** [bitnami/bitnami-docker-redmine#180]
### Name and Version

bitnami/redmine 4.2.4-debian-10-r0

### What steps will reproduce the bug?

I'm using EKS on AWS
Install redmine with postgresql thanks to the helm chart.
Redmine is working.
Do these commands : 
```
kubectl cp additionals $CONTAINER_NAME:/opt/bitnami/redmine/plugins/additionals --namespace redmine
kubectl cp redmine_saml $CONTAINER_NAME:/opt/bitnami/redmine/plugins/redmine_saml --namespace redmine
kubectl exec $CONTAINER_NAME --namespace redmine -- cp /opt/bitnami/redmine/plugins/redmine_saml/sample-saml-initializers.rb /opt/bitnami/redmine/config/initializers/saml.rb
kubectl exec $CONTAINER_NAME --namespace redmine -- /bin/bash -c "cd /opt/bitnami/redmine && bundle config set --local deployment 'false'"
kubectl exec $CONTAINER_NAME --namespace redmine -- /bin/bash -c "cd /opt/bitnami/redmine && bundle install"
kubectl exec $CONTAINER_NAME --namespace redmine -- /bin/bash -c "cd /opt/bitnami/redmine && bundle exec rake redmine:plugins:migrate RAILS_ENV=production"
kubectl exec $CONTAINER_NAME --namespace redmine -- touch /opt/bitnami/redmine/tmp/restart.txt
```

After that redmine is working with the new plugins. 

Then i delete the pod, kubectl delete pod <my pod> and it will try to restart but stay stucked in CrahshLoopBackOff

Here is the log
```
redmine-7d78d6f476-7b7np redmine redmine 14:13:34.08
redmine-7d78d6f476-7b7np redmine redmine 14:13:34.09 Welcome to the Bitnami redmine container
redmine-7d78d6f476-7b7np redmine redmine 14:13:34.09 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-redmine
redmine-7d78d6f476-7b7np redmine redmine 14:13:34.09 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-redmine/issues
redmine-7d78d6f476-7b7np redmine redmine 14:13:34.09
redmine-7d78d6f476-7b7np redmine redmine 14:13:34.10 INFO  ==> Validating settings in MYSQL_CLIENT_* env vars
redmine-7d78d6f476-7b7np redmine redmine 14:13:34.11 INFO  ==> Validating settings in POSTGRESQL_CLIENT_* env vars
redmine-7d78d6f476-7b7np redmine redmine 14:13:34.15 DEBUG ==> Validating settings in REDMINE_* environment variables...
redmine-7d78d6f476-7b7np redmine redmine 14:13:34.16 INFO  ==> Restoring persisted Redmine installation
redmine-7d78d6f476-7b7np redmine redmine 14:13:34.21 INFO  ==> Trying to connect to the database server
redmine-7d78d6f476-7b7np redmine redmine 14:13:34.21 DEBUG ==> Getting production.host from Redmine configuration
redmine-7d78d6f476-7b7np redmine redmine 14:13:34.22 DEBUG ==> Getting production.port from Redmine configuration
redmine-7d78d6f476-7b7np redmine redmine 14:13:34.24 DEBUG ==> Getting production.database from Redmine configuration
redmine-7d78d6f476-7b7np redmine redmine 14:13:34.26 DEBUG ==> Getting production.username from Redmine configuration
redmine-7d78d6f476-7b7np redmine redmine 14:13:34.27 DEBUG ==> Getting production.password from Redmine configuration
redmine-7d78d6f476-7b7np redmine redmine 14:13:34.29 DEBUG ==> Getting production.adapter from Redmine configuration
redmine-7d78d6f476-7b7np redmine  ?column?
redmine-7d78d6f476-7b7np redmine ----------
redmine-7d78d6f476-7b7np redmine         1
redmine-7d78d6f476-7b7np redmine (1 row)
redmine-7d78d6f476-7b7np redmine
redmine-7d78d6f476-7b7np redmine redmine 14:13:34.33 INFO  ==> Executing database migrations
redmine-7d78d6f476-7b7np redmine redmine 14:13:34.33 DEBUG ==> Generating secret tokens
redmine-7d78d6f476-7b7np redmine bundler: failed to load command: rake (/opt/bitnami/redmine/vendor/bundle/ruby/2.6.0/bin/rake)
redmine-7d78d6f476-7b7np redmine /opt/bitnami/ruby/lib/ruby/gems/2.6.0/gems/bundler-2.3.8/lib/bundler/definition.rb:397:in `ensure_equivalent_gemfile_and_lockfile': You are trying to install in deployment mode after changing (Bundler::ProductionError)
redmine-7d78d6f476-7b7np redmine your Gemfile. Run `bundle install` elsewhere and add the
redmine-7d78d6f476-7b7np redmine updated Gemfile.lock to version control.
redmine-7d78d6f476-7b7np redmine
redmine-7d78d6f476-7b7np redmine If this is a development machine, remove the /opt/bitnami/redmine/Gemfile freeze
redmine-7d78d6f476-7b7np redmine by running `bundle config unset deployment`.
redmine-7d78d6f476-7b7np redmine
redmine-7d78d6f476-7b7np redmine The list of sources changed
redmine-7d78d6f476-7b7np redmine The dependencies in your gemfile changed
redmine-7d78d6f476-7b7np redmine The gemspecs for path gems changed
redmine-7d78d6f476-7b7np redmine
redmine-7d78d6f476-7b7np redmine You have added to the Gemfile:
redmine-7d78d6f476-7b7np redmine * additionals
redmine-7d78d6f476-7b7np redmine * omniauth-saml (~> 1.10.3)
redmine-7d78d6f476-7b7np redmine * redmine_plugin_kit
redmine-7d78d6f476-7b7np redmine * shoulda
redmine-7d78d6f476-7b7np redmine 	from /opt/bitnami/ruby/lib/ruby/gems/2.6.0/gems/bundler-2.3.8/lib/bundler/runtime.rb:13:in `setup'
redmine-7d78d6f476-7b7np redmine 	from /opt/bitnami/ruby/lib/ruby/gems/2.6.0/gems/bundler-2.3.8/lib/bundler.rb:151:in `setup'
redmine-7d78d6f476-7b7np redmine 	from /opt/bitnami/ruby/lib/ruby/gems/2.6.0/gems/bundler-2.3.8/lib/bundler/setup.rb:20:in `block in <top (required)>'
redmine-7d78d6f476-7b7np redmine 	from /opt/bitnami/ruby/lib/ruby/gems/2.6.0/gems/bundler-2.3.8/lib/bundler/ui/shell.rb:136:in `with_level'
redmine-7d78d6f476-7b7np redmine 	from /opt/bitnami/ruby/lib/ruby/gems/2.6.0/gems/bundler-2.3.8/lib/bundler/ui/shell.rb:88:in `silence'
redmine-7d78d6f476-7b7np redmine 	from /opt/bitnami/ruby/lib/ruby/gems/2.6.0/gems/bundler-2.3.8/lib/bundler/setup.rb:20:in `<top (required)>'
redmine-7d78d6f476-7b7np redmine 	from /opt/bitnami/ruby/lib/ruby/gems/2.6.0/gems/bundler-2.3.8/lib/bundler/cli/exec.rb:56:in `require_relative'
redmine-7d78d6f476-7b7np redmine 	from /opt/bitnami/ruby/lib/ruby/gems/2.6.0/gems/bundler-2.3.8/lib/bundler/cli/exec.rb:56:in `kernel_load'
redmine-7d78d6f476-7b7np redmine 	from /opt/bitnami/ruby/lib/ruby/gems/2.6.0/gems/bundler-2.3.8/lib/bundler/cli/exec.rb:23:in `run'
redmine-7d78d6f476-7b7np redmine 	from /opt/bitnami/ruby/lib/ruby/gems/2.6.0/gems/bundler-2.3.8/lib/bundler/cli.rb:484:in `exec'
redmine-7d78d6f476-7b7np redmine 	from /opt/bitnami/ruby/lib/ruby/gems/2.6.0/gems/bundler-2.3.8/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
redmine-7d78d6f476-7b7np redmine 	from /opt/bitnami/ruby/lib/ruby/gems/2.6.0/gems/bundler-2.3.8/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
redmine-7d78d6f476-7b7np redmine 	from /opt/bitnami/ruby/lib/ruby/gems/2.6.0/gems/bundler-2.3.8/lib/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
redmine-7d78d6f476-7b7np redmine 	from /opt/bitnami/ruby/lib/ruby/gems/2.6.0/gems/bundler-2.3.8/lib/bundler/cli.rb:31:in `dispatch'
redmine-7d78d6f476-7b7np redmine 	from /opt/bitnami/ruby/lib/ruby/gems/2.6.0/gems/bundler-2.3.8/lib/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
redmine-7d78d6f476-7b7np redmine 	from /opt/bitnami/ruby/lib/ruby/gems/2.6.0/gems/bundler-2.3.8/lib/bundler/cli.rb:25:in `start'
redmine-7d78d6f476-7b7np redmine 	from /opt/bitnami/ruby/lib/ruby/gems/2.6.0/gems/bundler-2.3.8/exe/bundle:48:in `block in <top (required)>'
redmine-7d78d6f476-7b7np redmine 	from /opt/bitnami/ruby/lib/ruby/gems/2.6.0/gems/bundler-2.3.8/lib/bundler/friendly_errors.rb:103:in `with_friendly_errors'
redmine-7d78d6f476-7b7np redmine 	from /opt/bitnami/ruby/lib/ruby/gems/2.6.0/gems/bundler-2.3.8/exe/bundle:36:in `<top (required)>'
redmine-7d78d6f476-7b7np redmine 	from /opt/bitnami/ruby/bin/bundle:25:in `load'
redmine-7d78d6f476-7b7np redmine 	from /opt/bitnami/ruby/bin/bundle:25:in `<main>'
- redmine-7d78d6f476-7b7np › redmine
```

### What is the expected behavior?

redmine pod will restart smoothly

### What do you see instead?

redmine pod stay stuck

**Comment by carrodher** [comment]
Please, [note the Bitnami team is not actively monitoring GitHub Issues for this project](https://github.com/bitnami/bitnami-docker-redmine#community-supported-solution). This issue will stay open for 20 days to allow the community to contribute, after 15 days without activity the issue will be marked as stale being closed after 5 days.

If you would like to contribute to this container image by fixing a bug or adding a new feature feel free to create a PR, the Bitnami team will be happy to review it and provide feedback.
